// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYfnChSoTW1-ve9r6OLMCAZ_ug2c9pl3E',
    appId: '1:151929145674:web:037f8cb6469c9d6f79d9b3',
    messagingSenderId: '151929145674',
    projectId: 'diaghans',
    authDomain: 'diaghans.firebaseapp.com',
    databaseURL: 'https://diaghans.firebaseio.com',
    storageBucket: 'diaghans.appspot.com',
    measurementId: 'G-WM307LXR1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4LTPhLsYsLkk56QwNjBy0s09HBqPEGys',
    appId: '1:151929145674:android:35b7fbeeb8d15ee779d9b3',
    messagingSenderId: '151929145674',
    projectId: 'diaghans',
    databaseURL: 'https://diaghans.firebaseio.com',
    storageBucket: 'diaghans.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKaDs316HAzJLfg1lTXHSjKsEb7tr9Tk',
    appId: '1:151929145674:ios:5b767bca961f44f779d9b3',
    messagingSenderId: '151929145674',
    projectId: 'diaghans',
    databaseURL: 'https://diaghans.firebaseio.com',
    storageBucket: 'diaghans.appspot.com',
    androidClientId: '151929145674-2ttr06hnpfneom42c9itvmlskdruspq7.apps.googleusercontent.com',
    iosClientId: '151929145674-kr8t7hae68dsurot122ml4v77a63mfmn.apps.googleusercontent.com',
    iosBundleId: 'br.com.medtecno.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuKaDs316HAzJLfg1lTXHSjKsEb7tr9Tk',
    appId: '1:151929145674:ios:5b767bca961f44f779d9b3',
    messagingSenderId: '151929145674',
    projectId: 'diaghans',
    databaseURL: 'https://diaghans.firebaseio.com',
    storageBucket: 'diaghans.appspot.com',
    androidClientId: '151929145674-2ttr06hnpfneom42c9itvmlskdruspq7.apps.googleusercontent.com',
    iosClientId: '151929145674-kr8t7hae68dsurot122ml4v77a63mfmn.apps.googleusercontent.com',
    iosBundleId: 'br.com.medtecno.app',
  );
}
